services:
  - docker
install:
  - docker version
  - docker-compose version
  - git clone https://github.com/jarib/docker-setup
  - cd docker-setup
  - git checkout es6
  - cp ../docker-compose.override.yml ./
  - mkdir -p volumes volumes/metrics volumes/metrics/users collections volumes/search-es-snapshots volumes/search-es
  - chmod -R 777 volumes
  - cp search.testing.env search.env
  - cp snoop.testing.env snoop.env
  - docker-compose up -d
  - git clone https://github.com/hoover/testdata collections/testdata
  - sleep 30 && docker-compose logs search-es
script:
  - docker-compose run search-es bash -c 'curl "http://search-es:9200/_cluster/health?wait_for_status=yellow&timeout=50s"'

